#
# This is the adapted from the GENIE project Makefile.
# Machine specific flags and locations are read from 'make/Make.include'.
# Configuration options are read from 'make/Make.config' generated by the 'configure' script.
#
# Author: Costas Andreopoulos <costas.andreopoulos \at stfc.ac.uk>
#         Joshua Berger <josh.berger@pitt.edu>
#

# Include machine specific flags and locations (inc. files & libs)
#
include $(GENIE)/src/make/Make.include
include Make.include

GSOLFLUX_PATH=$(shell pwd)
BIN_PATH=$(GSOLFLUX_PATH)/bin
BIN_INSTALLATION_PATH=$(INSTALLATION_PATH)/bin

GENIE_LIBS  = $(shell $(GENIE)/src/scripts/setup/genie-config --libs)
SOLTRACK_LIBS = -L$(GOPT_WITH_SOLTRACK_LIB) -lSolTrack

LIBRARIES := $(SOLTRACK_LIBS) $(LIBRARIES) $(CERN_LIBRARIES) $(GENIE_LIBS) 

CPP_INCLUDES += -I$(GOPT_WITH_SOLTRACK_INC)

TGT_BASE =  gsolflux

TGT = $(addprefix $(BIN_PATH)/,$(TGT_BASE))


OBJDIR = obj

# Use either one of the following lines:
#STDOBJ = ../obj/SolTrack.o ../obj/SolTrack_RiseSet.o


# Default target: make all:
all: $(TGT)

%.o: %.cxx
	$(CXX) $(CXXFLAGS) -MMD -MP -c $(CPP_INCLUDES) $< -o $@

$(BIN_PATH)/gsolflux: gSolFlux.o $(call find_libs,gsolflux)
	@echo "** Building gsolflux"
	$(LD) $(LDFLAGS) gSolFlux.o $(LIBRARIES) -o $(BIN_PATH)/gsolflux

install: FORCE
	[ -d ${INSTALLATION_PATH}         ] || mkdir ${INSTALLATION_PATH}
	cd ${INSTALLATION_PATH}
	[ -d ${BIN_INSTALLATION_PATH}     ] || mkdir ${BIN_INSTALLATION_PATH}
	cp ${BIN_PATH}/* ${BIN_INSTALLATION_PATH}/
	cd ${GSOLFLUX_PATH}

purge: FORCE
	$(RM) *.o *~ *.d core

clean: FORCE
	$(RM) *.o *~ *.d core
	$(RM) $(TGT)

distclean: FORCE
	$(RM) $(patsubst $(BIN_DIR),$(INSTALLATION_PATH),$(TGT))

FORCE:

-include $(wildcard *.d)
